sudo: true
dist: xenial
python:
  - 3.7
language: python
services:
  - xvfb
install:
  - pip install -r requirements.txt
before_script:
#  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
env:
  global:
    - DISPLAY=:99.0
  matrix:
    - TOX_ENV=python
    - TOX_ENV=flake8
    - TOX_ENV=docs
script:
  - tox -e $TOX_ENV
#  - ./ci/build.sh all
#after_success:
#  - ./ci/deploy-artifacts.sh
